=== VarunMehta1/HWKC/HardwareKeyCreator/HardwareKeyOrders.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Order">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Keys"/>
			</xs:sequence>
			<xs:attribute name="csn" use="required" type="xs:integer"/>
			<xs:attribute name="customerName" use="required"/>
			<xs:attribute name="deliveryNumber" use="required" type="xs:NCName"/>
			<xs:attribute name="licenseCreateDate" use="required" type="xs:integer"/>
			<xs:attribute name="orderNumber" use="required" type="xs:NCName"/>
			<xs:attribute name="po" use="required" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Keys">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="Key"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Key">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Licenses"/>
			</xs:sequence>
			<xs:attribute name="assetAction" use="required" type="xs:NCName"/>
			<xs:attribute name="expirationDate" use="required" type="xs:integer"/>
			<xs:attribute name="name" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Licenses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="License"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="License">
		<xs:complexType>
			<xs:attribute name="activationCode" use="required"/>
			<xs:attribute name="assetId" use="required" type="xs:NMTOKEN"/>
			<xs:attribute name="name" use="required"/>
			<xs:attribute name="smartId" use="required" type="xs:NCName"/>
			<xs:attribute name="smartName" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== VarunMehta1/HWKC/HardwareKeyCreator/XMLFile1.xml
<?xml version="1.0" encoding="UTF-8"?>

-<Order po="75678" deliveryNumber="a415E000000AjHkQAK" orderNumber="ED00370970" csn="22266900" customerName="CRESCENT ELECTRIC SUPPLY COMPANY" licenseCreateDate="040820" xsi:noNamespaceSchemaLocation="HardwareKeyOrders.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">


	-<Keys>


		-<Key assetAction="New" expirationDate="000001" name="Key Group 1">


			-<Licenses>

				<License name="PAC Machine Edition" activationCode="90284448-F096-4BEE-A329-07B43E87E27E" assetId="9-34607401-003-001" smartName="Machine Edition v9.7 Professional Development Suite 700 Points" smartId="ME97MBP001"/>

			</Licenses>

		</Key>


		-<Key assetAction="New" expirationDate="000002" name="Key Group 2">


			-<Licenses>

				<License name="PAC Change Management" activationCode="90284448-F096-4BEE-A329-07B43E87E27F" assetId="9-34607401-006-001" smartName="Change Management v9.5 1 CALs" smartId="CM95001"/>

			</Licenses>

		</Key>


		-<Key assetAction="New" expirationDate="000003" name="Key Group 3">


			-<Licenses>

				<License name="PAC Machine Edition" activationCode="90284448-F096-4BEE-A329-07B43E87E27G" assetId="9-34607401-009-001" smartName="Machine Edition v9.5 QuickPanel Control CE Development Software" smartId="ME95CSCEMK"/>

			</Licenses>

		</Key>


		-<Key assetAction="New" expirationDate="000004" name="Key Group 4">


			-<Licenses>

				<License name="PAC Change Management" activationCode="90284448-F096-4BEE-A329-07B43E87E27H" assetId="9-34607401-012-001" smartName="Change Management v9.7 10 CALs" smartId="CM97010"/>

			</Licenses>

		</Key>

	</Keys>

</Order>
